java.lang.IllegalArgumentException: Item at position 33 requires 3 spans but GridLayoutManager has only 2 spans
Cause: mLayoutManager.setSpanCount cause FC
Measure: change to call mLayoutManager.requestLayout()

2020-03-20 14:01:49.288 13925-13925/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.tunm.gallerypro, PID: 13925
    java.lang.IllegalArgumentException: Item at position 33 requires 3 spans but GridLayoutManager has only 2 spans.
        at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:548)
        at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1519)
        at android.support.v7.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1333)
        at android.support.v7.widget.LinearLayoutManager.scrollVerticallyBy(LinearLayoutManager.java:1077)
        at android.support.v7.widget.GridLayoutManager.scrollVerticallyBy(GridLayoutManager.java:381)
        at android.support.v7.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:4960)