java.lang.IllegalArgumentException: Comparison method violates its general contract
at com.tubeeapp.gallerypro.fragments.list.normal.albums.AlbumsAdapter.sort(AlbumsAdapter.java:88)
at com.tubeeapp.gallerypro.fragments.list.normal.abstraction.BaseListViewAdapter.changeSortingMode(BaseListViewAdapter.java:75)
at com.tubeeapp.gallerypro.fragments.list.normal.albums.AlbumsFragment.onGetAlbumSuccess(AlbumsFragment.java:486)
at com.tubeeapp.gallerypro.fragments.list.normal.albums.presenter.AlbumsPresenterImpl$1.onResponse(AlbumsPresenterImpl.java:40)

Cause: null values aren't handled properly